<?php

namespace Database\Seeders;

use App\Models\DetectionRule;
use Illuminate\Database\Seeder;

class DetectionRulesSeeder extends Seeder
{
    public function run(): void
    {
        $rules = [
            // ============================================
            // SSH/Authentication Rules (for Agent Logs)
            // ============================================
            [
                'name' => 'SSH Failed Login Attempt',
                'slug' => 'ssh-failed-login',
                'description' => 'Detects failed SSH login attempts on monitored servers.',
                'category' => 'authentication',
                'severity' => 'medium',
                'conditions' => [
                    'log_types' => ['auth', 'syslog'],
                    'patterns' => ['Failed password', 'authentication failure', 'Failed publickey'],
                    'match_type' => 'any',
                ],
                'actions' => [['type' => 'log'], ['type' => 'alert']],
                'threshold' => 1,
                'time_window' => 60,
                'cooldown' => 300,
                'is_active' => true,
                'is_system' => true,
                'mitre_tactics' => ['TA0006'],
                'mitre_techniques' => ['T1110'],
            ],
            [
                'name' => 'SSH Brute Force Attack',
                'slug' => 'ssh-brute-force',
                'description' => 'Detects multiple failed SSH login attempts indicating a brute force attack.',
                'category' => 'brute_force',
                'severity' => 'high',
                'conditions' => [
                    'log_types' => ['auth', 'syslog'],
                    'patterns' => ['Failed password for', 'Failed password for invalid user'],
                    'match_type' => 'any',
                ],
                'actions' => [['type' => 'log'], ['type' => 'alert'], ['type' => 'notify']],
                'threshold' => 5,
                'time_window' => 300,
                'cooldown' => 3600,
                'is_active' => true,
                'is_system' => true,
                'mitre_tactics' => ['TA0006'],
                'mitre_techniques' => ['T1110', 'T1110.001'],
            ],
            [
                'name' => 'Invalid User SSH Attempt',
                'slug' => 'ssh-invalid-user',
                'description' => 'Detects SSH login attempts with non-existent usernames.',
                'category' => 'authentication',
                'severity' => 'high',
                'conditions' => [
                    'log_types' => ['auth', 'syslog'],
                    'patterns' => ['Invalid user', 'invalid user'],
                    'match_type' => 'any',
                ],
                'actions' => [['type' => 'log'], ['type' => 'alert']],
                'threshold' => 1,
                'time_window' => 60,
                'cooldown' => 300,
                'is_active' => true,
                'is_system' => true,
                'mitre_tactics' => ['TA0006'],
                'mitre_techniques' => ['T1078'],
            ],
            [
                'name' => 'Successful Root Login',
                'slug' => 'root-login-success',
                'description' => 'Detects successful root login which may indicate unauthorized access.',
                'category' => 'authentication',
                'severity' => 'high',
                'conditions' => [
                    'log_types' => ['auth', 'syslog'],
                    'patterns' => ['Accepted password for root', 'Accepted publickey for root', 'session opened for user root'],
                    'match_type' => 'any',
                ],
                'actions' => [['type' => 'log'], ['type' => 'alert'], ['type' => 'notify']],
                'threshold' => 1,
                'time_window' => 60,
                'cooldown' => 600,
                'is_active' => true,
                'is_system' => true,
                'mitre_tactics' => ['TA0004'],
                'mitre_techniques' => ['T1078.003'],
            ],
            
            // ============================================
            // Privilege Escalation Rules
            // ============================================
            [
                'name' => 'Sudo Command Executed',
                'slug' => 'sudo-command',
                'description' => 'Detects sudo command execution for privilege escalation monitoring.',
                'category' => 'privilege_escalation',
                'severity' => 'low',
                'conditions' => [
                    'log_types' => ['auth', 'syslog'],
                    'patterns' => ['sudo:', 'COMMAND='],
                    'match_type' => 'all',
                ],
                'actions' => [['type' => 'log']],
                'threshold' => 1,
                'time_window' => 60,
                'cooldown' => 60,
                'is_active' => true,
                'is_system' => true,
                'mitre_tactics' => ['TA0004'],
                'mitre_techniques' => ['T1548.003'],
            ],
            [
                'name' => 'Sudo Authentication Failure',
                'slug' => 'sudo-auth-failure',
                'description' => 'Detects failed sudo authentication attempts.',
                'category' => 'privilege_escalation',
                'severity' => 'medium',
                'conditions' => [
                    'log_types' => ['auth', 'syslog'],
                    'patterns' => ['sudo', 'authentication failure', '3 incorrect password attempts'],
                    'match_type' => 'any',
                ],
                'actions' => [['type' => 'log'], ['type' => 'alert']],
                'threshold' => 1,
                'time_window' => 60,
                'cooldown' => 300,
                'is_active' => true,
                'is_system' => true,
                'mitre_tactics' => ['TA0004'],
                'mitre_techniques' => ['T1548'],
            ],
            [
                'name' => 'User Added to Sudoers',
                'slug' => 'sudoers-modified',
                'description' => 'Detects modifications to sudoers file or group.',
                'category' => 'privilege_escalation',
                'severity' => 'critical',
                'conditions' => [
                    'log_types' => ['auth', 'syslog'],
                    'patterns' => ['added to group sudo', 'visudo', '/etc/sudoers'],
                    'match_type' => 'any',
                ],
                'actions' => [['type' => 'log'], ['type' => 'alert'], ['type' => 'notify']],
                'threshold' => 1,
                'time_window' => 60,
                'cooldown' => 3600,
                'is_active' => true,
                'is_system' => true,
                'mitre_tactics' => ['TA0003', 'TA0004'],
                'mitre_techniques' => ['T1548.003'],
            ],

            // ============================================
            // System Security Rules
            // ============================================
            [
                'name' => 'Service Started/Stopped',
                'slug' => 'service-change',
                'description' => 'Detects system service state changes.',
                'category' => 'system',
                'severity' => 'low',
                'conditions' => [
                    'log_types' => ['syslog'],
                    'patterns' => ['Started', 'Stopped', 'systemd'],
                    'match_type' => 'any',
                ],
                'actions' => [['type' => 'log']],
                'threshold' => 1,
                'time_window' => 60,
                'cooldown' => 60,
                'is_active' => false, // Disabled by default (too noisy)
                'is_system' => true,
                'mitre_tactics' => ['TA0003'],
                'mitre_techniques' => ['T1543'],
            ],
            [
                'name' => 'Firewall Rule Changed',
                'slug' => 'firewall-change',
                'description' => 'Detects changes to firewall rules.',
                'category' => 'system',
                'severity' => 'high',
                'conditions' => [
                    'log_types' => ['syslog', 'auth'],
                    'patterns' => ['iptables', 'ufw', 'firewalld', 'nftables'],
                    'match_type' => 'any',
                ],
                'actions' => [['type' => 'log'], ['type' => 'alert']],
                'threshold' => 1,
                'time_window' => 60,
                'cooldown' => 300,
                'is_active' => true,
                'is_system' => true,
                'mitre_tactics' => ['TA0005'],
                'mitre_techniques' => ['T1562.004'],
            ],
            [
                'name' => 'New User Created',
                'slug' => 'user-created',
                'description' => 'Detects creation of new user accounts.',
                'category' => 'persistence',
                'severity' => 'medium',
                'conditions' => [
                    'log_types' => ['auth', 'syslog'],
                    'patterns' => ['useradd', 'adduser', 'new user'],
                    'match_type' => 'any',
                ],
                'actions' => [['type' => 'log'], ['type' => 'alert']],
                'threshold' => 1,
                'time_window' => 60,
                'cooldown' => 600,
                'is_active' => true,
                'is_system' => true,
                'mitre_tactics' => ['TA0003'],
                'mitre_techniques' => ['T1136.001'],
            ],
            [
                'name' => 'User Deleted',
                'slug' => 'user-deleted',
                'description' => 'Detects deletion of user accounts.',
                'category' => 'system',
                'severity' => 'medium',
                'conditions' => [
                    'log_types' => ['auth', 'syslog'],
                    'patterns' => ['userdel', 'deluser', 'delete user'],
                    'match_type' => 'any',
                ],
                'actions' => [['type' => 'log'], ['type' => 'alert']],
                'threshold' => 1,
                'time_window' => 60,
                'cooldown' => 600,
                'is_active' => true,
                'is_system' => true,
                'mitre_tactics' => ['TA0040'],
                'mitre_techniques' => ['T1531'],
            ],

            // ============================================
            // Malware/Suspicious Activity Rules
            // ============================================
            [
                'name' => 'Suspicious Command Execution',
                'slug' => 'suspicious-command',
                'description' => 'Detects execution of potentially malicious commands.',
                'category' => 'malware',
                'severity' => 'critical',
                'conditions' => [
                    'log_types' => ['auth', 'syslog'],
                    'patterns' => [
                        'wget http',
                        'curl http',
                        '/dev/tcp/',
                        'base64 -d',
                        'python -c',
                        'perl -e',
                        'nc -e',
                        'bash -i',
                    ],
                    'match_type' => 'any',
                ],
                'actions' => [['type' => 'log'], ['type' => 'alert'], ['type' => 'notify']],
                'threshold' => 1,
                'time_window' => 60,
                'cooldown' => 300,
                'is_active' => true,
                'is_system' => true,
                'mitre_tactics' => ['TA0002'],
                'mitre_techniques' => ['T1059'],
            ],
            [
                'name' => 'Reverse Shell Detection',
                'slug' => 'reverse-shell',
                'description' => 'Detects potential reverse shell connections.',
                'category' => 'malware',
                'severity' => 'critical',
                'conditions' => [
                    'log_types' => ['auth', 'syslog'],
                    'patterns' => [
                        '/dev/tcp/',
                        'bash -i >& /dev',
                        'nc -e /bin',
                        'mkfifo',
                        'telnet.*\|.*sh',
                    ],
                    'match_type' => 'any',
                ],
                'actions' => [['type' => 'log'], ['type' => 'alert'], ['type' => 'notify']],
                'threshold' => 1,
                'time_window' => 60,
                'cooldown' => 60,
                'is_active' => true,
                'is_system' => true,
                'mitre_tactics' => ['TA0011'],
                'mitre_techniques' => ['T1059.004'],
            ],
            [
                'name' => 'Cron Job Modified',
                'slug' => 'cron-modified',
                'description' => 'Detects modifications to cron jobs which could indicate persistence.',
                'category' => 'persistence',
                'severity' => 'medium',
                'conditions' => [
                    'log_types' => ['syslog', 'cron'],
                    'patterns' => ['crontab', 'REPLACE', 'LIST', '/etc/cron'],
                    'match_type' => 'any',
                ],
                'actions' => [['type' => 'log'], ['type' => 'alert']],
                'threshold' => 1,
                'time_window' => 60,
                'cooldown' => 600,
                'is_active' => true,
                'is_system' => true,
                'mitre_tactics' => ['TA0003'],
                'mitre_techniques' => ['T1053.003'],
            ],

            // ============================================
            // Web Server Rules (Apache/Nginx)
            // ============================================
            [
                'name' => 'Web Server Error Spike',
                'slug' => 'web-error-spike',
                'description' => 'Detects spike in web server errors indicating potential attack.',
                'category' => 'web',
                'severity' => 'medium',
                'conditions' => [
                    'log_types' => ['apache', 'nginx'],
                    'patterns' => ['error', '500', '502', '503', '504'],
                    'match_type' => 'any',
                ],
                'actions' => [['type' => 'log'], ['type' => 'alert']],
                'threshold' => 10,
                'time_window' => 300,
                'cooldown' => 600,
                'is_active' => true,
                'is_system' => true,
                'mitre_tactics' => ['TA0040'],
                'mitre_techniques' => ['T1499'],
            ],
            [
                'name' => 'SQL Injection Attempt',
                'slug' => 'sql-injection',
                'description' => 'Detects potential SQL injection attempts in web logs.',
                'category' => 'web',
                'severity' => 'high',
                'conditions' => [
                    'log_types' => ['apache', 'nginx'],
                    'patterns' => [
                        'UNION SELECT',
                        'OR 1=1',
                        "' OR '",
                        'DROP TABLE',
                        'INSERT INTO',
                        '--',
                        'SLEEP(',
                    ],
                    'match_type' => 'any',
                ],
                'actions' => [['type' => 'log'], ['type' => 'alert'], ['type' => 'notify']],
                'threshold' => 1,
                'time_window' => 60,
                'cooldown' => 300,
                'is_active' => true,
                'is_system' => true,
                'mitre_tactics' => ['TA0001'],
                'mitre_techniques' => ['T1190'],
            ],
            [
                'name' => 'Path Traversal Attempt',
                'slug' => 'path-traversal',
                'description' => 'Detects path traversal/directory traversal attacks.',
                'category' => 'web',
                'severity' => 'high',
                'conditions' => [
                    'log_types' => ['apache', 'nginx'],
                    'patterns' => ['../', '..\\', '/etc/passwd', '/etc/shadow', 'win.ini'],
                    'match_type' => 'any',
                ],
                'actions' => [['type' => 'log'], ['type' => 'alert']],
                'threshold' => 1,
                'time_window' => 60,
                'cooldown' => 300,
                'is_active' => true,
                'is_system' => true,
                'mitre_tactics' => ['TA0001'],
                'mitre_techniques' => ['T1083'],
            ],

            // ============================================
            // Application Server Rules
            // ============================================
            [
                'name' => 'XSS Attack Attempt',
                'slug' => 'xss-attack',
                'description' => 'Detects Cross-Site Scripting (XSS) attack attempts.',
                'category' => 'web',
                'severity' => 'high',
                'conditions' => [
                    'log_types' => ['apache', 'nginx', 'app'],
                    'patterns' => [
                        '<script>',
                        'javascript:',
                        'onerror=',
                        'onload=',
                        'onclick=',
                        'onmouseover=',
                        'alert(',
                        'document.cookie',
                        'eval(',
                    ],
                    'match_type' => 'any',
                ],
                'actions' => [['type' => 'log'], ['type' => 'alert']],
                'threshold' => 1,
                'time_window' => 60,
                'cooldown' => 300,
                'is_active' => true,
                'is_system' => true,
                'mitre_tactics' => ['TA0001'],
                'mitre_techniques' => ['T1189'],
            ],
            [
                'name' => 'Command Injection Attempt',
                'slug' => 'command-injection',
                'description' => 'Detects OS command injection attempts in application logs.',
                'category' => 'web',
                'severity' => 'critical',
                'conditions' => [
                    'log_types' => ['apache', 'nginx', 'app'],
                    'patterns' => [
                        '; ls',
                        '| cat',
                        '&& whoami',
                        '| id',
                        '; rm -rf',
                        '`id`',
                        '$(whoami)',
                        '/bin/bash',
                        '/bin/sh',
                    ],
                    'match_type' => 'any',
                ],
                'actions' => [['type' => 'log'], ['type' => 'alert'], ['type' => 'notify']],
                'threshold' => 1,
                'time_window' => 60,
                'cooldown' => 300,
                'is_active' => true,
                'is_system' => true,
                'mitre_tactics' => ['TA0002'],
                'mitre_techniques' => ['T1059'],
            ],
            [
                'name' => 'File Upload Attack',
                'slug' => 'file-upload-attack',
                'description' => 'Detects malicious file upload attempts.',
                'category' => 'web',
                'severity' => 'high',
                'conditions' => [
                    'log_types' => ['apache', 'nginx', 'app'],
                    'patterns' => [
                        '.php uploaded',
                        '.jsp uploaded',
                        '.asp uploaded',
                        '.exe uploaded',
                        '.sh uploaded',
                        'shell.php',
                        'webshell',
                        'c99.php',
                        'r57.php',
                    ],
                    'match_type' => 'any',
                ],
                'actions' => [['type' => 'log'], ['type' => 'alert'], ['type' => 'notify']],
                'threshold' => 1,
                'time_window' => 60,
                'cooldown' => 300,
                'is_active' => true,
                'is_system' => true,
                'mitre_tactics' => ['TA0001'],
                'mitre_techniques' => ['T1190'],
            ],
            [
                'name' => 'LDAP Injection Attempt',
                'slug' => 'ldap-injection',
                'description' => 'Detects LDAP injection attempts.',
                'category' => 'web',
                'severity' => 'high',
                'conditions' => [
                    'log_types' => ['apache', 'nginx', 'app'],
                    'patterns' => [
                        '*)(uid=',
                        '*)(cn=',
                        '*()|',
                        '*)(objectClass=',
                    ],
                    'match_type' => 'any',
                ],
                'actions' => [['type' => 'log'], ['type' => 'alert']],
                'threshold' => 1,
                'time_window' => 60,
                'cooldown' => 300,
                'is_active' => true,
                'is_system' => true,
                'mitre_tactics' => ['TA0001'],
                'mitre_techniques' => ['T1190'],
            ],
            [
                'name' => 'XML External Entity (XXE)',
                'slug' => 'xxe-attack',
                'description' => 'Detects XML External Entity injection attempts.',
                'category' => 'web',
                'severity' => 'critical',
                'conditions' => [
                    'log_types' => ['apache', 'nginx', 'app'],
                    'patterns' => [
                        '<!ENTITY',
                        'SYSTEM "file:',
                        'SYSTEM "http:',
                        '<!DOCTYPE',
                        'file:///etc/passwd',
                    ],
                    'match_type' => 'any',
                ],
                'actions' => [['type' => 'log'], ['type' => 'alert'], ['type' => 'notify']],
                'threshold' => 1,
                'time_window' => 60,
                'cooldown' => 300,
                'is_active' => true,
                'is_system' => true,
                'mitre_tactics' => ['TA0009'],
                'mitre_techniques' => ['T1213'],
            ],
            [
                'name' => 'Server-Side Request Forgery (SSRF)',
                'slug' => 'ssrf-attack',
                'description' => 'Detects SSRF attack attempts.',
                'category' => 'web',
                'severity' => 'high',
                'conditions' => [
                    'log_types' => ['apache', 'nginx', 'app'],
                    'patterns' => [
                        'http://127.0.0.1',
                        'http://localhost',
                        'http://169.254.169.254',
                        'http://0.0.0.0',
                        'file:///',
                        'gopher://',
                        'dict://',
                    ],
                    'match_type' => 'any',
                ],
                'actions' => [['type' => 'log'], ['type' => 'alert']],
                'threshold' => 1,
                'time_window' => 60,
                'cooldown' => 300,
                'is_active' => true,
                'is_system' => true,
                'mitre_tactics' => ['TA0009'],
                'mitre_techniques' => ['T1090'],
            ],
            [
                'name' => 'Sensitive Data Exposure',
                'slug' => 'sensitive-data-exposure',
                'description' => 'Detects potential sensitive data exposure in logs.',
                'category' => 'data_exfiltration',
                'severity' => 'critical',
                'conditions' => [
                    'log_types' => ['app', 'syslog'],
                    'patterns' => [
                        'password=',
                        'api_key=',
                        'secret_key=',
                        'credit_card',
                        'ssn=',
                        'token=',
                        'Authorization: Bearer',
                    ],
                    'match_type' => 'any',
                ],
                'actions' => [['type' => 'log'], ['type' => 'alert'], ['type' => 'notify']],
                'threshold' => 1,
                'time_window' => 60,
                'cooldown' => 600,
                'is_active' => true,
                'is_system' => true,
                'mitre_tactics' => ['TA0010'],
                'mitre_techniques' => ['T1530'],
            ],
            [
                'name' => 'Application Error Spike',
                'slug' => 'app-error-spike',
                'description' => 'Detects unusual spike in application errors.',
                'category' => 'application',
                'severity' => 'medium',
                'conditions' => [
                    'log_types' => ['app', 'laravel', 'nodejs', 'python'],
                    'patterns' => [
                        'Exception',
                        'Error:',
                        'Fatal error',
                        'Uncaught',
                        'Stack trace',
                        'SQLSTATE',
                    ],
                    'match_type' => 'any',
                ],
                'actions' => [['type' => 'log'], ['type' => 'alert']],
                'threshold' => 10,
                'time_window' => 300,
                'cooldown' => 600,
                'is_active' => true,
                'is_system' => true,
                'mitre_tactics' => ['TA0040'],
                'mitre_techniques' => ['T1499'],
            ],
            [
                'name' => 'Database Connection Failure',
                'slug' => 'db-connection-failure',
                'description' => 'Detects database connection failures.',
                'category' => 'application',
                'severity' => 'high',
                'conditions' => [
                    'log_types' => ['app', 'mysql', 'postgresql'],
                    'patterns' => [
                        'Connection refused',
                        'Access denied for user',
                        'Too many connections',
                        'Connection timed out',
                        'SQLSTATE[HY000]',
                    ],
                    'match_type' => 'any',
                ],
                'actions' => [['type' => 'log'], ['type' => 'alert'], ['type' => 'notify']],
                'threshold' => 3,
                'time_window' => 300,
                'cooldown' => 600,
                'is_active' => true,
                'is_system' => true,
                'mitre_tactics' => ['TA0040'],
                'mitre_techniques' => ['T1499.004'],
            ],
            [
                'name' => 'API Rate Limit Exceeded',
                'slug' => 'api-rate-limit',
                'description' => 'Detects API rate limit violations indicating potential abuse.',
                'category' => 'application',
                'severity' => 'medium',
                'conditions' => [
                    'log_types' => ['app', 'nginx', 'apache'],
                    'patterns' => [
                        'rate limit',
                        'Too Many Requests',
                        '429',
                        'throttle',
                        'quota exceeded',
                    ],
                    'match_type' => 'any',
                ],
                'actions' => [['type' => 'log'], ['type' => 'alert']],
                'threshold' => 5,
                'time_window' => 300,
                'cooldown' => 600,
                'is_active' => true,
                'is_system' => true,
                'mitre_tactics' => ['TA0040'],
                'mitre_techniques' => ['T1499'],
            ],
            [
                'name' => 'JWT Token Manipulation',
                'slug' => 'jwt-manipulation',
                'description' => 'Detects JWT token manipulation attempts.',
                'category' => 'authentication',
                'severity' => 'high',
                'conditions' => [
                    'log_types' => ['app'],
                    'patterns' => [
                        'Invalid signature',
                        'Token expired',
                        'JWT decode error',
                        'alg: none',
                        'Invalid token',
                    ],
                    'match_type' => 'any',
                ],
                'actions' => [['type' => 'log'], ['type' => 'alert']],
                'threshold' => 3,
                'time_window' => 300,
                'cooldown' => 600,
                'is_active' => true,
                'is_system' => true,
                'mitre_tactics' => ['TA0006'],
                'mitre_techniques' => ['T1528'],
            ],
            [
                'name' => 'Session Hijacking Attempt',
                'slug' => 'session-hijacking',
                'description' => 'Detects potential session hijacking attempts.',
                'category' => 'authentication',
                'severity' => 'critical',
                'conditions' => [
                    'log_types' => ['app'],
                    'patterns' => [
                        'Session ID mismatch',
                        'IP address changed',
                        'User agent changed',
                        'Session fixation',
                        'Invalid session',
                    ],
                    'match_type' => 'any',
                ],
                'actions' => [['type' => 'log'], ['type' => 'alert'], ['type' => 'notify']],
                'threshold' => 1,
                'time_window' => 60,
                'cooldown' => 300,
                'is_active' => true,
                'is_system' => true,
                'mitre_tactics' => ['TA0006'],
                'mitre_techniques' => ['T1539'],
            ],
            [
                'name' => 'Mass Assignment Attack',
                'slug' => 'mass-assignment',
                'description' => 'Detects mass assignment vulnerability exploitation.',
                'category' => 'web',
                'severity' => 'high',
                'conditions' => [
                    'log_types' => ['app', 'laravel'],
                    'patterns' => [
                        'MassAssignmentException',
                        'Add [',
                        'fillable',
                        'guarded',
                        'is_admin',
                        'role_id',
                    ],
                    'match_type' => 'any',
                ],
                'actions' => [['type' => 'log'], ['type' => 'alert']],
                'threshold' => 1,
                'time_window' => 60,
                'cooldown' => 300,
                'is_active' => true,
                'is_system' => true,
                'mitre_tactics' => ['TA0004'],
                'mitre_techniques' => ['T1078'],
            ],
            [
                'name' => 'Insecure Deserialization',
                'slug' => 'insecure-deserialization',
                'description' => 'Detects insecure deserialization attacks.',
                'category' => 'web',
                'severity' => 'critical',
                'conditions' => [
                    'log_types' => ['app'],
                    'patterns' => [
                        'unserialize()',
                        'O:',
                        '__wakeup',
                        '__destruct',
                        'pickle.loads',
                        'yaml.load',
                    ],
                    'match_type' => 'any',
                ],
                'actions' => [['type' => 'log'], ['type' => 'alert'], ['type' => 'notify']],
                'threshold' => 1,
                'time_window' => 60,
                'cooldown' => 300,
                'is_active' => true,
                'is_system' => true,
                'mitre_tactics' => ['TA0002'],
                'mitre_techniques' => ['T1059'],
            ],
            [
                'name' => 'Docker Container Escape',
                'slug' => 'container-escape',
                'description' => 'Detects potential container escape attempts.',
                'category' => 'system',
                'severity' => 'critical',
                'conditions' => [
                    'log_types' => ['syslog', 'docker'],
                    'patterns' => [
                        '--privileged',
                        '/var/run/docker.sock',
                        'CAP_SYS_ADMIN',
                        'nsenter',
                        'cgroup escape',
                    ],
                    'match_type' => 'any',
                ],
                'actions' => [['type' => 'log'], ['type' => 'alert'], ['type' => 'notify']],
                'threshold' => 1,
                'time_window' => 60,
                'cooldown' => 300,
                'is_active' => true,
                'is_system' => true,
                'mitre_tactics' => ['TA0004'],
                'mitre_techniques' => ['T1611'],
            ],
            [
                'name' => 'Kubernetes Security Event',
                'slug' => 'k8s-security-event',
                'description' => 'Detects Kubernetes security-related events.',
                'category' => 'system',
                'severity' => 'high',
                'conditions' => [
                    'log_types' => ['kubernetes', 'k8s'],
                    'patterns' => [
                        'Forbidden',
                        'Unauthorized',
                        'secrets',
                        'exec into pod',
                        'privileged: true',
                    ],
                    'match_type' => 'any',
                ],
                'actions' => [['type' => 'log'], ['type' => 'alert']],
                'threshold' => 1,
                'time_window' => 60,
                'cooldown' => 300,
                'is_active' => true,
                'is_system' => true,
                'mitre_tactics' => ['TA0004'],
                'mitre_techniques' => ['T1610'],
            ],

            // ============================================
            // Database Server Rules (MySQL/MariaDB/PostgreSQL)
            // ============================================
            [
                'name' => 'MySQL Authentication Failure',
                'slug' => 'mysql-auth-failure',
                'description' => 'Detects failed MySQL/MariaDB authentication attempts.',
                'category' => 'authentication',
                'severity' => 'medium',
                'conditions' => [
                    'log_types' => ['mysql', 'syslog'],
                    'patterns' => [
                        'Access denied for user',
                        'authentication failure',
                        'failed to authenticate',
                    ],
                    'match_type' => 'any',
                ],
                'actions' => [['type' => 'log'], ['type' => 'alert']],
                'threshold' => 1,
                'time_window' => 60,
                'cooldown' => 300,
                'is_active' => true,
                'is_system' => true,
                'mitre_tactics' => ['TA0006'],
                'mitre_techniques' => ['T1110'],
            ],
            [
                'name' => 'MySQL Brute Force Attack',
                'slug' => 'mysql-brute-force',
                'description' => 'Detects multiple failed MySQL login attempts indicating brute force.',
                'category' => 'brute_force',
                'severity' => 'high',
                'conditions' => [
                    'log_types' => ['mysql'],
                    'patterns' => [
                        'Access denied for user',
                        'Host is blocked',
                    ],
                    'match_type' => 'any',
                ],
                'actions' => [['type' => 'log'], ['type' => 'alert'], ['type' => 'notify']],
                'threshold' => 5,
                'time_window' => 300,
                'cooldown' => 3600,
                'is_active' => true,
                'is_system' => true,
                'mitre_tactics' => ['TA0006'],
                'mitre_techniques' => ['T1110'],
            ],
            [
                'name' => 'MySQL Suspicious Query',
                'slug' => 'mysql-suspicious-query',
                'description' => 'Detects potentially dangerous SQL queries.',
                'category' => 'data_exfiltration',
                'severity' => 'high',
                'conditions' => [
                    'log_types' => ['mysql'],
                    'patterns' => [
                        'INTO OUTFILE',
                        'INTO DUMPFILE',
                        'LOAD_FILE',
                        'LOAD DATA INFILE',
                        'information_schema',
                        'mysql.user',
                    ],
                    'match_type' => 'any',
                ],
                'actions' => [['type' => 'log'], ['type' => 'alert'], ['type' => 'notify']],
                'threshold' => 1,
                'time_window' => 60,
                'cooldown' => 300,
                'is_active' => true,
                'is_system' => true,
                'mitre_tactics' => ['TA0009'],
                'mitre_techniques' => ['T1005'],
            ],
            [
                'name' => 'MySQL Privilege Escalation',
                'slug' => 'mysql-privilege-escalation',
                'description' => 'Detects attempts to escalate privileges in MySQL.',
                'category' => 'privilege_escalation',
                'severity' => 'critical',
                'conditions' => [
                    'log_types' => ['mysql'],
                    'patterns' => [
                        'GRANT ALL',
                        'GRANT SUPER',
                        'CREATE USER',
                        'ALTER USER',
                        'SET PASSWORD',
                        'GRANT PROCESS',
                        'GRANT FILE',
                    ],
                    'match_type' => 'any',
                ],
                'actions' => [['type' => 'log'], ['type' => 'alert'], ['type' => 'notify']],
                'threshold' => 1,
                'time_window' => 60,
                'cooldown' => 600,
                'is_active' => true,
                'is_system' => true,
                'mitre_tactics' => ['TA0004'],
                'mitre_techniques' => ['T1078'],
            ],
            [
                'name' => 'MySQL Data Export',
                'slug' => 'mysql-data-export',
                'description' => 'Detects large data exports from MySQL.',
                'category' => 'data_exfiltration',
                'severity' => 'high',
                'conditions' => [
                    'log_types' => ['mysql'],
                    'patterns' => [
                        'mysqldump',
                        'SELECT * FROM',
                        'INTO OUTFILE',
                        'pg_dump',
                    ],
                    'match_type' => 'any',
                ],
                'actions' => [['type' => 'log'], ['type' => 'alert']],
                'threshold' => 1,
                'time_window' => 60,
                'cooldown' => 600,
                'is_active' => true,
                'is_system' => true,
                'mitre_tactics' => ['TA0010'],
                'mitre_techniques' => ['T1048'],
            ],
            [
                'name' => 'Database Schema Change',
                'slug' => 'db-schema-change',
                'description' => 'Detects database schema modifications.',
                'category' => 'system',
                'severity' => 'medium',
                'conditions' => [
                    'log_types' => ['mysql', 'postgresql'],
                    'patterns' => [
                        'DROP TABLE',
                        'DROP DATABASE',
                        'TRUNCATE',
                        'ALTER TABLE',
                        'CREATE TABLE',
                    ],
                    'match_type' => 'any',
                ],
                'actions' => [['type' => 'log'], ['type' => 'alert']],
                'threshold' => 1,
                'time_window' => 60,
                'cooldown' => 300,
                'is_active' => true,
                'is_system' => true,
                'mitre_tactics' => ['TA0040'],
                'mitre_techniques' => ['T1485'],
            ],
            [
                'name' => 'Database Replication Issue',
                'slug' => 'db-replication-issue',
                'description' => 'Detects database replication problems.',
                'category' => 'system',
                'severity' => 'high',
                'conditions' => [
                    'log_types' => ['mysql'],
                    'patterns' => [
                        'Slave SQL thread',
                        'replication error',
                        'Slave I/O thread',
                        'relay log',
                        'binlog error',
                    ],
                    'match_type' => 'any',
                ],
                'actions' => [['type' => 'log'], ['type' => 'alert'], ['type' => 'notify']],
                'threshold' => 1,
                'time_window' => 60,
                'cooldown' => 600,
                'is_active' => true,
                'is_system' => true,
                'mitre_tactics' => ['TA0040'],
                'mitre_techniques' => ['T1499'],
            ],
            [
                'name' => 'PostgreSQL Authentication Failure',
                'slug' => 'postgresql-auth-failure',
                'description' => 'Detects failed PostgreSQL authentication attempts.',
                'category' => 'authentication',
                'severity' => 'medium',
                'conditions' => [
                    'log_types' => ['postgresql'],
                    'patterns' => [
                        'password authentication failed',
                        'no pg_hba.conf entry',
                        'authentication failed',
                        'FATAL:  password',
                    ],
                    'match_type' => 'any',
                ],
                'actions' => [['type' => 'log'], ['type' => 'alert']],
                'threshold' => 1,
                'time_window' => 60,
                'cooldown' => 300,
                'is_active' => true,
                'is_system' => true,
                'mitre_tactics' => ['TA0006'],
                'mitre_techniques' => ['T1110'],
            ],

            // ============================================
            // Original Brute Force Rules (for Web Login)
            // ============================================
            [
                'name' => 'Login Brute Force - IP Based',
                'slug' => 'brute-force-ip',
                'description' => 'Detects multiple failed login attempts from the same IP address within a short time window. Automatically blocks the source IP when the threshold is reached.',
                'category' => 'brute_force',
                'severity' => 'high',
                'conditions' => ['ip_based'],
                'actions' => [
                    ['type' => 'block_ip', 'duration' => 6],
                    ['type' => 'log'],
                    ['type' => 'notify', 'channel' => 'email'],
                ],
                'threshold' => 5,
                'time_window' => 300,
                'cooldown' => 3600,
                'is_active' => true,
                'is_system' => true,
                'mitre_tactics' => ['TA0006'],
                'mitre_techniques' => ['T1110', 'T1110.001'],
            ],
            [
                'name' => 'Login Brute Force - Account Based',
                'slug' => 'brute-force-account',
                'description' => 'Detects multiple failed login attempts targeting the same account from different IPs.',
                'category' => 'brute_force',
                'severity' => 'high',
                'conditions' => ['email_based'],
                'actions' => [
                    ['type' => 'log'],
                    ['type' => 'notify', 'channel' => 'email'],
                ],
                'threshold' => 10,
                'time_window' => 600, // 10 minutes
                'cooldown' => 3600,
                'is_active' => true,
                'is_system' => true,
                'mitre_tactics' => ['TA0006'],
                'mitre_techniques' => ['T1110', 'T1110.003'], // Password Spraying
            ],
            [
                'name' => 'Aggressive Brute Force Attack',
                'slug' => 'brute-force-aggressive',
                'description' => 'Detects aggressive brute force attacks with automatic IP blocking.',
                'category' => 'brute_force',
                'severity' => 'critical',
                'conditions' => ['ip_based'],
                'actions' => [
                    ['type' => 'block_ip', 'duration' => 24], // Block for 24 hours
                    ['type' => 'log'],
                    ['type' => 'notify', 'channel' => 'email'],
                ],
                'threshold' => 20,
                'time_window' => 300, // 5 minutes
                'cooldown' => 86400, // 24 hours
                'is_active' => true,
                'is_system' => true,
                'mitre_tactics' => ['TA0006'],
                'mitre_techniques' => ['T1110'],
            ],
            [
                'name' => 'Distributed Brute Force',
                'slug' => 'brute-force-distributed',
                'description' => 'Detects distributed brute force attacks targeting multiple accounts.',
                'category' => 'brute_force',
                'severity' => 'critical',
                'conditions' => ['ip_based', 'email_based'],
                'actions' => [
                    ['type' => 'block_ip', 'duration' => 48],
                    ['type' => 'log'],
                    ['type' => 'notify', 'channel' => 'email'],
                ],
                'threshold' => 50,
                'time_window' => 900, // 15 minutes
                'cooldown' => 86400,
                'is_active' => true,
                'is_system' => true,
                'mitre_tactics' => ['TA0006'],
                'mitre_techniques' => ['T1110.003'], // Password Spraying
            ],
            [
                'name' => 'Slow Brute Force',
                'slug' => 'brute-force-slow',
                'description' => 'Detects slow brute force attacks spread over a longer time period.',
                'category' => 'brute_force',
                'severity' => 'medium',
                'conditions' => ['ip_based'],
                'actions' => [
                    ['type' => 'log'],
                    ['type' => 'notify', 'channel' => 'email'],
                ],
                'threshold' => 15,
                'time_window' => 3600, // 1 hour
                'cooldown' => 7200,
                'is_active' => true,
                'is_system' => true,
                'mitre_tactics' => ['TA0006'],
                'mitre_techniques' => ['T1110'],
            ],
            [
                'name' => 'Credential Stuffing Detection',
                'slug' => 'credential-stuffing',
                'description' => 'Detects credential stuffing attacks using leaked credentials.',
                'category' => 'brute_force',
                'severity' => 'high',
                'conditions' => ['ip_based', 'email_based'],
                'actions' => [
                    ['type' => 'block_ip', 'duration' => 12],
                    ['type' => 'log'],
                    ['type' => 'notify', 'channel' => 'email'],
                ],
                'threshold' => 30,
                'time_window' => 600, // 10 minutes
                'cooldown' => 3600,
                'is_active' => true,
                'is_system' => true,
                'mitre_tactics' => ['TA0006'],
                'mitre_techniques' => ['T1110.004'], // Credential Stuffing
            ],
        ];

        foreach ($rules as $rule) {
            DetectionRule::updateOrCreate(
                ['slug' => $rule['slug']],
                $rule
            );
        }
    }
}
